"""Add unique constraint for category name per user

Revision ID: ff9ee8cc45e7
Revises: e2ca6440a449
Create Date: 2025-09-01 14:59:52.231080

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff9ee8cc45e7"
down_revision: Union[str, Sequence[str], None] = "e2ca6440a449"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_user_category_name", "categories", ["user_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_category_name", "categories", type_="unique")
    # ### end Alembic commands ###
